export const features = [
  { id: 'own-html', old: true, new: false },
  { id: 'javascript', old: true, new: false },
  { id: 'closed-websites', old: true, new: false },
  { id: 'view-parts', old: true, new: false },
  { id: 'pwa', old: false, new: true },
  { id: 'workspaces', old: true, new: true },
  { id: 'multi-websites', old: true, new: true },
  { id: 'apps', old: true, new: true },
  { id: 'themes', old: true, new: true },
  { id: 'multivendors', old: false, new: true },
  { id: 'assembly-options', old: true, new: true },
  { id: 'bread-crumb', old: true, new: true },
  { id: 'full-text-search-box', old: true, new: true },
  { id: 'store-flag-locator', old: false, new: true },
  { id: 'welcome-message', old: true, new: false },
  { id: 'meta', old: true, new: true },
  { id: 'department-links', old: true, new: true },
  { id: 'department-navigator', old: true, new: false },
  { id: 'search-title', old: true, new: false },
  { id: 'product-query-string', old: true, new: false },
  { id: 'product-quick-view', old: true, new: false },
  { id: 'product-page-title', old: true, new: false },
  { id: 'product-name', old: true, new: true },
  { id: 'product-brand', old: true, new: true },
  { id: 'product-image', old: true, new: true },
  { id: 'product-reference', old: true, new: false },
  { id: 'product-price', old: true, new: false },
  { id: 'sku-reference', old: true, new: false },
  { id: 'sku-price', old: true, new: false },
  { id: 'stock-keeping', old: true, new: false },
  { id: 'sku-rich-selection', old: true, new: false },
  { id: 'sku-selection', old: true, new: false },
  { id: 'other-payment-methods', old: true, new: true },
  { id: 'delivery', old: true, new: true },
  { id: 'shipping-value', old: true, new: true },
  { id: 'stock-keeping-reward-values', old: true, new: false },
  { id: 'stock-keeping-unit-service', old: true, new: false },
  { id: 'buy-together', old: true, new: false },
  { id: 'product-description', old: true, new: true },
  { id: 'product-description-short', old: true, new: true },
  { id: 'product-specification', old: true, new: true },
  { id: 'stock-keeping-unit-attributes', old: true, new: false },
  { id: 'stock-keeping-unit-measures', old: true, new: false },
  { id: 'product-tag', old: true, new: false },
  { id: 'page-search', old: true, new: true },
  { id: 'buy-button', old: true, new: true },
  { id: 'buy-in-page', old: true, new: true },
  { id: 'stock-keeping-unit-amount-and-unit-selection', old: true, new: false },
  { id: 'evaluation-rate', old: true, new: false },
  { id: 'user-review', old: true, new: false },
  { id: 'gift-list-insert-sku', old: true, new: false },
  { id: 'gift-list-form-v2', old: true, new: false },
  { id: 'hightlight', old: true, new: false },
  { id: 'discount-hightlight', old: true, new: true },
  { id: 'seller-options', old: true, new: false },
  { id: 'seller-description', old: true, new: true },
  { id: 'seller-info', old: true, new: true },
  { id: 'sales-channel-drop-list', old: true, new: false },
  { id: 'content-place-holder-QVVT', old: true, new: false },
  { id: 'content-place-holder-QVCT', old: true, new: false },
  { id: 'content-place-holder-QCCT', old: true, new: false },
  { id: 'content-place-holder-similares', old: true, new: false },
  { id: 'content-place-holder-acessorios', old: true, new: false },
  { id: 'content-place-holder-sugestoes', old: true, new: false },
  { id: 'rich-snippets', old: true, new: false },
]

export const storeComponents = [
  {
    name: 'Store Components',
    docs: 'https://github.com/vtex-apps/store-components',
  },
  {
    name: 'Store Header',
    docs: 'https://github.com/vtex-apps/store-header',
  },
  {
    name: 'Store Footer',
    docs: 'https://github.com/vtex-apps/store-footer',
  },
  {
    name: 'Shelf',
    docs: 'https://github.com/vtex-apps/shelf',
  },
  {
    name: 'Carousel',
    docs: 'https://github.com/vtex-apps/carousel',
  },
  {
    name: 'Menu',
    docs: 'https://github.com/vtex-apps/menu',
  },
  {
    name: 'Minicart',
    docs: 'https://github.com/vtex-apps/minicart',
  },
  {
    name: 'Telemarketing',
    docs: 'https://github.com/vtex-apps/telemarketing',
  },
  {
    name: 'Login',
    docs: 'https://github.com/vtex-apps/login',
  },
  {
    name: 'Category Menu',
    docs: 'https://github.com/vtex-apps/category-menu',
  },
  {
    name: 'Breadcrumb',
    docs: 'https://github.com/vtex-apps/breadcrumb',
  },
  {
    name: 'Search Result',
    docs: 'https://github.com/vtex-apps/search-result',
  },
  {
    name: 'Product Details',
    docs: 'https://github.com/vtex-apps/product-details',
  },
  {
    name: 'Address Locator (for deliveries)',
    docs: 'https://github.com/vtex-apps/address-locator',
  },
  {
    name: 'Flex Layout',
    docs: 'https://github.com/vtex-apps/flex-layout',
  },
  {
    name: 'My Account',
    docs: 'https://github.com/vtex-apps/my-account',
  },
  {
    name: 'My Account Commons',
    docs: 'https://github.com/vtex-apps/my-account-commons',
  },
  {
    name: 'Product Customizer',
    docs: 'https://github.com/vtex-apps/product-customizer',
  },
  {
    name: 'Product Kit',
    docs: 'https://github.com/vtex-apps/product-kit',
  },
  {
    name: 'Product Summary',
    docs: 'https://github.com/vtex-apps/product-summary',
  },
  {
    name: 'Store Icons',
    docs: 'https://github.com/vtex-apps/store-icons',
  },
  {
    name: 'Rich Text',
    docs: 'https://github.com/vtex-apps/rich-text',
  },
  {
    name: 'Wishlist',
    docs: 'https://github.com/vtex-apps/wishlist',
    construction: true,
  },
  {
    name: 'Order Placed',
    docs: 'https://github.com/vtex-apps/order-placed',
    construction: true,
  },
]

export const storePixel = [
  {
    name: 'Facebook Pixel',
    docs: 'https://github.com/vtex-apps/facebook-pixel',
  },
  {
    name: 'Google Adwords',
    docs: 'https://github.com/vtex-apps/google-adwords',
  },
  {
    name: 'Google Tag Manager',
    docs: 'https://github.com/vtex-apps/google-tag-manager',
  },
]
